package com.java.project;

public enum States {

	ANDRA_PRADESH, ARUNACHAL_PRADESH, UTTAR_PRADESH, 
	HIMACHAL_PRADESH, UTTARAKHAND, PUNJAB, HARYANA, 
	DELHI, BIHAR, WEST_BENGAL, TELENGANA, KARNATAKA, 
	KERALA, TAMIL_NADU, RAJASTHAN, JHARKHAND, CHHATTISHGARH, 
	ODISHA, MANIPUR, TRIPURA, GOA, SIKKIM, MEGHALAYA, MIZORAM, 
	TELANGANA, GUJARAT, MAHARASTHRA, MADHYA_PRADESH,
	ANDAMAN_AND_NICOBAR_ISLAND, DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU;
	
}
